query currentUser {
  currentUser {
      nodeId
      id
      username
      userEmails(first: 10) {
        nodes {
          email
          isVerified
        }
      }
      isAdmin
      name
  }
}
