#import "./userFragment.gql"

mutation ResetPassword(
  $userId: Int!
  $token: String!
  $newPassword: String!
) {
  resetPassword(
    input: { userId: $userId, token: $token, newPassword: $newPassword }
  ) {
    user {
      ...user
    }
  }
}