#!/bin/bash

# Output SQL from DB

# Where am I?
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR/..

echo -n "Dumping DB..."
echo "DROP SCHEMA postgraphile_watch CASCADE;" | psql -X "$DATABASE_URL" >/dev/null 2>&1
pg_dump -s -O -f data/schema.sql "$DATABASE_URL"

# We don't want postgraphile_watch in our schema dump, and `--exclude-schema`
# doesn't like event triggers, so drop it, do the dump, and restore it. Only
# run this on development!
cat /docker-entrypoint-initdb.d/0001_watch_fixtures.sql | psql -X "$DATABASE_URL" >/dev/null 2>&1
# /docker-entrypoint/initdb.d is the automatically mounted folder for initialization scripts, equivalent path from project root: /db/init/
# see: https://docs.docker.com/samples/library/postgres/#initialization-scripts

# watch_fixtures.sql may be out of sync with your current postgraphile version. To be super safe you should get it from here:
# node_modules/postgraphile/node_modules/graphile-build-pg/res/watch-fixtures.sql
# (currently not possible with node_modules in a separate docker-volume)

echo " done"
